### ISSUE TITLE
单面打印页码排列位置有问题

### ISSUE THREAD

**Issue by Lyanf** [suchot/LZUThesis2017#5]
根据兰州大学的要求

> 单面复印时页码排在页脚居中位置，双面复印时页码分别按左右侧排列。

但是目前在使用模板时，页码都是居右的，应该是不符合任意一种情况。

如果在documentclass里面添加[twoside]则符合双面打印的要求

**Comment by suchot** [comment]
毕业的时候默认是打单面还是双面？

**Comment by Lyanf** [comment]
> 毕业的时候默认是打单面还是双面？

额..这个规范里面说都是可以的，不存在默认的情况，但是我本人是打算打成双面的，这样做成一本书方便翻阅一点儿？（还便宜）
具体情况学长可以参阅
> http://jwc.lzu.edu.cn/lzupage/2019/04/29/N20190429181817.html?tdsourcetag=s_pctim_aiomsg

里面有一个具体的写作规范的附件。学长闲下来可以看一下~
