### ISSUE TITLE
摘要页没有页码显示

### ISSUE THREAD

**Issue by Lyanf** [suchot/LZUThesis2017#7]
按照兰大现行的要求，摘要页应该是要有页码的，但是现在模板默认是不显示摘要页的页码。
我注意到样式文件里面将中英文摘要命令里的
> \thispagestyle{frontmatterstyle}

注释掉了，现在默认使用的是empty样式，建议将默认的改为frontmatterstyle

**Comment by suchot** [comment]
你可以把改好的pull上来嘛. 感觉修正了好多
